# -*- coding: utf-8 -*-
"""전봇대 프로젝트 1.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3S4AAkux2Il6mmm6zgGkfzQS25_hkWP
"""

# ✅ STEP 1: YOLOv8 설치
!pip install -q ultralytics

# ✅ STEP 2: 파일 업로드 (직접 이미지 선택)
from google.colab import files
uploaded = files.upload()

# ✅ STEP 3: 경로 확인
import os

# 업로드한 파일명 얻기
uploaded_filename = next(iter(uploaded))
image_path = os.path.abspath(uploaded_filename)
print("📂 이미지 경로:", image_path)

# ✅ STEP 4: 라이브러리 임포트
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import pandas as pd

# ✅ STEP 5: YOLOv8 모델 로드
model = YOLO("yolov8n.pt")

# ✅ STEP 6: 객체 감지 실행
results = model(image_path)

# ✅ STEP 7: 시각화용 이미지 생성
result_image = results[0].plot()

# ✅ STEP 8: 결과 이미지 출력
plt.figure(figsize=(10, 8))
plt.imshow(cv2.cvtColor(result_image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.title("YOLOv8 Object Detection Result")
plt.show()

# ✅ STEP 9: 감지된 객체 정보 추출
detected_objects = []
for box in results[0].boxes:
    cls_id = int(box.cls[0])
    label = model.names[cls_id]
    conf = float(box.conf[0])
    xyxy = box.xyxy[0].tolist()
    detected_objects.append({
        "Label": label,
        "Confidence": round(conf, 2),
        "BBox [x1, y1, x2, y2]": [round(x, 1) for x in xyxy]
    })

# ✅ STEP 10: 객체 정보 출력
pd.DataFrame(detected_objects)